// Code generated by protoc-gen-go. DO NOT EDIT.
// source: srx_grpc_v6.proto

package srx_grpc_v6

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PduRequest struct {
	Data                 []byte   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Length               uint32   `protobuf:"varint,2,opt,name=length,proto3" json:"length,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PduRequest) Reset()         { *m = PduRequest{} }
func (m *PduRequest) String() string { return proto.CompactTextString(m) }
func (*PduRequest) ProtoMessage()    {}
func (*PduRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6d819656a476f83, []int{0}
}

func (m *PduRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PduRequest.Unmarshal(m, b)
}
func (m *PduRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PduRequest.Marshal(b, m, deterministic)
}
func (m *PduRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PduRequest.Merge(m, src)
}
func (m *PduRequest) XXX_Size() int {
	return xxx_messageInfo_PduRequest.Size(m)
}
func (m *PduRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PduRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PduRequest proto.InternalMessageInfo

func (m *PduRequest) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *PduRequest) GetLength() uint32 {
	if m != nil {
		return m.Length
	}
	return 0
}

type PduResponse struct {
	Data                 []byte   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Length               uint32   `protobuf:"varint,2,opt,name=length,proto3" json:"length,omitempty"`
	ValidationStatus     uint32   `protobuf:"varint,3,opt,name=validation_status,json=validationStatus,proto3" json:"validation_status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PduResponse) Reset()         { *m = PduResponse{} }
func (m *PduResponse) String() string { return proto.CompactTextString(m) }
func (*PduResponse) ProtoMessage()    {}
func (*PduResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6d819656a476f83, []int{1}
}

func (m *PduResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PduResponse.Unmarshal(m, b)
}
func (m *PduResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PduResponse.Marshal(b, m, deterministic)
}
func (m *PduResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PduResponse.Merge(m, src)
}
func (m *PduResponse) XXX_Size() int {
	return xxx_messageInfo_PduResponse.Size(m)
}
func (m *PduResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PduResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PduResponse proto.InternalMessageInfo

func (m *PduResponse) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *PduResponse) GetLength() uint32 {
	if m != nil {
		return m.Length
	}
	return 0
}

func (m *PduResponse) GetValidationStatus() uint32 {
	if m != nil {
		return m.ValidationStatus
	}
	return 0
}

type ProxyHelloRequest struct {
	Type                 uint32   `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`
	Version              uint32   `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	Reserved             uint32   `protobuf:"varint,3,opt,name=reserved,proto3" json:"reserved,omitempty"`
	Zero                 uint32   `protobuf:"varint,4,opt,name=zero,proto3" json:"zero,omitempty"`
	Length               uint32   `protobuf:"varint,5,opt,name=length,proto3" json:"length,omitempty"`
	ProxyIdentifier      uint32   `protobuf:"varint,6,opt,name=proxyIdentifier,proto3" json:"proxyIdentifier,omitempty"`
	Asn                  uint32   `protobuf:"varint,7,opt,name=asn,proto3" json:"asn,omitempty"`
	NoPeerAS             uint32   `protobuf:"varint,8,opt,name=noPeerAS,proto3" json:"noPeerAS,omitempty"`
	PeerAS               uint32   `protobuf:"varint,9,opt,name=peerAS,proto3" json:"peerAS,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProxyHelloRequest) Reset()         { *m = ProxyHelloRequest{} }
func (m *ProxyHelloRequest) String() string { return proto.CompactTextString(m) }
func (*ProxyHelloRequest) ProtoMessage()    {}
func (*ProxyHelloRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6d819656a476f83, []int{2}
}

func (m *ProxyHelloRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProxyHelloRequest.Unmarshal(m, b)
}
func (m *ProxyHelloRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProxyHelloRequest.Marshal(b, m, deterministic)
}
func (m *ProxyHelloRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProxyHelloRequest.Merge(m, src)
}
func (m *ProxyHelloRequest) XXX_Size() int {
	return xxx_messageInfo_ProxyHelloRequest.Size(m)
}
func (m *ProxyHelloRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ProxyHelloRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ProxyHelloRequest proto.InternalMessageInfo

func (m *ProxyHelloRequest) GetType() uint32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *ProxyHelloRequest) GetVersion() uint32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *ProxyHelloRequest) GetReserved() uint32 {
	if m != nil {
		return m.Reserved
	}
	return 0
}

func (m *ProxyHelloRequest) GetZero() uint32 {
	if m != nil {
		return m.Zero
	}
	return 0
}

func (m *ProxyHelloRequest) GetLength() uint32 {
	if m != nil {
		return m.Length
	}
	return 0
}

func (m *ProxyHelloRequest) GetProxyIdentifier() uint32 {
	if m != nil {
		return m.ProxyIdentifier
	}
	return 0
}

func (m *ProxyHelloRequest) GetAsn() uint32 {
	if m != nil {
		return m.Asn
	}
	return 0
}

func (m *ProxyHelloRequest) GetNoPeerAS() uint32 {
	if m != nil {
		return m.NoPeerAS
	}
	return 0
}

func (m *ProxyHelloRequest) GetPeerAS() uint32 {
	if m != nil {
		return m.PeerAS
	}
	return 0
}

type ProxyHelloResponse struct {
	Type                 uint32   `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`
	Version              uint32   `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	Reserved             uint32   `protobuf:"varint,3,opt,name=reserved,proto3" json:"reserved,omitempty"`
	Zero                 uint32   `protobuf:"varint,4,opt,name=zero,proto3" json:"zero,omitempty"`
	Length               uint32   `protobuf:"varint,5,opt,name=length,proto3" json:"length,omitempty"`
	ProxyIdentifier      uint32   `protobuf:"varint,6,opt,name=proxyIdentifier,proto3" json:"proxyIdentifier,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProxyHelloResponse) Reset()         { *m = ProxyHelloResponse{} }
func (m *ProxyHelloResponse) String() string { return proto.CompactTextString(m) }
func (*ProxyHelloResponse) ProtoMessage()    {}
func (*ProxyHelloResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6d819656a476f83, []int{3}
}

func (m *ProxyHelloResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProxyHelloResponse.Unmarshal(m, b)
}
func (m *ProxyHelloResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProxyHelloResponse.Marshal(b, m, deterministic)
}
func (m *ProxyHelloResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProxyHelloResponse.Merge(m, src)
}
func (m *ProxyHelloResponse) XXX_Size() int {
	return xxx_messageInfo_ProxyHelloResponse.Size(m)
}
func (m *ProxyHelloResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ProxyHelloResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ProxyHelloResponse proto.InternalMessageInfo

func (m *ProxyHelloResponse) GetType() uint32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *ProxyHelloResponse) GetVersion() uint32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *ProxyHelloResponse) GetReserved() uint32 {
	if m != nil {
		return m.Reserved
	}
	return 0
}

func (m *ProxyHelloResponse) GetZero() uint32 {
	if m != nil {
		return m.Zero
	}
	return 0
}

func (m *ProxyHelloResponse) GetLength() uint32 {
	if m != nil {
		return m.Length
	}
	return 0
}

func (m *ProxyHelloResponse) GetProxyIdentifier() uint32 {
	if m != nil {
		return m.ProxyIdentifier
	}
	return 0
}

type ProxyGoodByeRequest struct {
	Type                 uint32   `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`
	KeepWindow           uint32   `protobuf:"varint,2,opt,name=keepWindow,proto3" json:"keepWindow,omitempty"`
	Reserved             uint32   `protobuf:"varint,3,opt,name=reserved,proto3" json:"reserved,omitempty"`
	Zero                 uint32   `protobuf:"varint,4,opt,name=zero,proto3" json:"zero,omitempty"`
	Length               uint32   `protobuf:"varint,5,opt,name=length,proto3" json:"length,omitempty"`
	GrpcClientID         uint32   `protobuf:"varint,6,opt,name=grpcClientID,proto3" json:"grpcClientID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProxyGoodByeRequest) Reset()         { *m = ProxyGoodByeRequest{} }
func (m *ProxyGoodByeRequest) String() string { return proto.CompactTextString(m) }
func (*ProxyGoodByeRequest) ProtoMessage()    {}
func (*ProxyGoodByeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6d819656a476f83, []int{4}
}

func (m *ProxyGoodByeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProxyGoodByeRequest.Unmarshal(m, b)
}
func (m *ProxyGoodByeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProxyGoodByeRequest.Marshal(b, m, deterministic)
}
func (m *ProxyGoodByeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProxyGoodByeRequest.Merge(m, src)
}
func (m *ProxyGoodByeRequest) XXX_Size() int {
	return xxx_messageInfo_ProxyGoodByeRequest.Size(m)
}
func (m *ProxyGoodByeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ProxyGoodByeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ProxyGoodByeRequest proto.InternalMessageInfo

func (m *ProxyGoodByeRequest) GetType() uint32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *ProxyGoodByeRequest) GetKeepWindow() uint32 {
	if m != nil {
		return m.KeepWindow
	}
	return 0
}

func (m *ProxyGoodByeRequest) GetReserved() uint32 {
	if m != nil {
		return m.Reserved
	}
	return 0
}

func (m *ProxyGoodByeRequest) GetZero() uint32 {
	if m != nil {
		return m.Zero
	}
	return 0
}

func (m *ProxyGoodByeRequest) GetLength() uint32 {
	if m != nil {
		return m.Length
	}
	return 0
}

func (m *ProxyGoodByeRequest) GetGrpcClientID() uint32 {
	if m != nil {
		return m.GrpcClientID
	}
	return 0
}

type ProxyGoodByeResponse struct {
	Status               bool     `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProxyGoodByeResponse) Reset()         { *m = ProxyGoodByeResponse{} }
func (m *ProxyGoodByeResponse) String() string { return proto.CompactTextString(m) }
func (*ProxyGoodByeResponse) ProtoMessage()    {}
func (*ProxyGoodByeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6d819656a476f83, []int{5}
}

func (m *ProxyGoodByeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProxyGoodByeResponse.Unmarshal(m, b)
}
func (m *ProxyGoodByeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProxyGoodByeResponse.Marshal(b, m, deterministic)
}
func (m *ProxyGoodByeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProxyGoodByeResponse.Merge(m, src)
}
func (m *ProxyGoodByeResponse) XXX_Size() int {
	return xxx_messageInfo_ProxyGoodByeResponse.Size(m)
}
func (m *ProxyGoodByeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ProxyGoodByeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ProxyGoodByeResponse proto.InternalMessageInfo

func (m *ProxyGoodByeResponse) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

type ProxyBasicHeader struct {
	Type                 uint32   `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`
	Flags                uint32   `protobuf:"varint,2,opt,name=flags,proto3" json:"flags,omitempty"`
	RoaResSrc            uint32   `protobuf:"varint,3,opt,name=roaResSrc,proto3" json:"roaResSrc,omitempty"`
	BgpsecResSrc         uint32   `protobuf:"varint,4,opt,name=bgpsecResSrc,proto3" json:"bgpsecResSrc,omitempty"`
	AspaResSrc           uint32   `protobuf:"varint,5,opt,name=aspaResSrc,proto3" json:"aspaResSrc,omitempty"`
	Reserved             uint32   `protobuf:"varint,6,opt,name=reserved,proto3" json:"reserved,omitempty"`
	AsType               uint32   `protobuf:"varint,7,opt,name=asType,proto3" json:"asType,omitempty"`
	AsRelType            uint32   `protobuf:"varint,8,opt,name=asRelType,proto3" json:"asRelType,omitempty"`
	Length               uint32   `protobuf:"varint,9,opt,name=length,proto3" json:"length,omitempty"`
	RoaDefRes            uint32   `protobuf:"varint,10,opt,name=roaDefRes,proto3" json:"roaDefRes,omitempty"`
	BgpsecDefRes         uint32   `protobuf:"varint,11,opt,name=bgpsecDefRes,proto3" json:"bgpsecDefRes,omitempty"`
	AspaDefRes           uint32   `protobuf:"varint,12,opt,name=aspaDefRes,proto3" json:"aspaDefRes,omitempty"`
	PrefixLen            uint32   `protobuf:"varint,13,opt,name=prefixLen,proto3" json:"prefixLen,omitempty"`
	RequestToken         uint32   `protobuf:"varint,14,opt,name=requestToken,proto3" json:"requestToken,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProxyBasicHeader) Reset()         { *m = ProxyBasicHeader{} }
func (m *ProxyBasicHeader) String() string { return proto.CompactTextString(m) }
func (*ProxyBasicHeader) ProtoMessage()    {}
func (*ProxyBasicHeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6d819656a476f83, []int{6}
}

func (m *ProxyBasicHeader) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProxyBasicHeader.Unmarshal(m, b)
}
func (m *ProxyBasicHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProxyBasicHeader.Marshal(b, m, deterministic)
}
func (m *ProxyBasicHeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProxyBasicHeader.Merge(m, src)
}
func (m *ProxyBasicHeader) XXX_Size() int {
	return xxx_messageInfo_ProxyBasicHeader.Size(m)
}
func (m *ProxyBasicHeader) XXX_DiscardUnknown() {
	xxx_messageInfo_ProxyBasicHeader.DiscardUnknown(m)
}

var xxx_messageInfo_ProxyBasicHeader proto.InternalMessageInfo

func (m *ProxyBasicHeader) GetType() uint32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *ProxyBasicHeader) GetFlags() uint32 {
	if m != nil {
		return m.Flags
	}
	return 0
}

func (m *ProxyBasicHeader) GetRoaResSrc() uint32 {
	if m != nil {
		return m.RoaResSrc
	}
	return 0
}

func (m *ProxyBasicHeader) GetBgpsecResSrc() uint32 {
	if m != nil {
		return m.BgpsecResSrc
	}
	return 0
}

func (m *ProxyBasicHeader) GetAspaResSrc() uint32 {
	if m != nil {
		return m.AspaResSrc
	}
	return 0
}

func (m *ProxyBasicHeader) GetReserved() uint32 {
	if m != nil {
		return m.Reserved
	}
	return 0
}

func (m *ProxyBasicHeader) GetAsType() uint32 {
	if m != nil {
		return m.AsType
	}
	return 0
}

func (m *ProxyBasicHeader) GetAsRelType() uint32 {
	if m != nil {
		return m.AsRelType
	}
	return 0
}

func (m *ProxyBasicHeader) GetLength() uint32 {
	if m != nil {
		return m.Length
	}
	return 0
}

func (m *ProxyBasicHeader) GetRoaDefRes() uint32 {
	if m != nil {
		return m.RoaDefRes
	}
	return 0
}

func (m *ProxyBasicHeader) GetBgpsecDefRes() uint32 {
	if m != nil {
		return m.BgpsecDefRes
	}
	return 0
}

func (m *ProxyBasicHeader) GetAspaDefRes() uint32 {
	if m != nil {
		return m.AspaDefRes
	}
	return 0
}

func (m *ProxyBasicHeader) GetPrefixLen() uint32 {
	if m != nil {
		return m.PrefixLen
	}
	return 0
}

func (m *ProxyBasicHeader) GetRequestToken() uint32 {
	if m != nil {
		return m.RequestToken
	}
	return 0
}

type IPv4Address struct {
	// Types that are valid to be assigned to AddressOneof:
	//	*IPv4Address_U32
	//	*IPv4Address_U8
	AddressOneof         isIPv4Address_AddressOneof `protobuf_oneof:"address_oneof"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *IPv4Address) Reset()         { *m = IPv4Address{} }
func (m *IPv4Address) String() string { return proto.CompactTextString(m) }
func (*IPv4Address) ProtoMessage()    {}
func (*IPv4Address) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6d819656a476f83, []int{7}
}

func (m *IPv4Address) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IPv4Address.Unmarshal(m, b)
}
func (m *IPv4Address) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IPv4Address.Marshal(b, m, deterministic)
}
func (m *IPv4Address) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IPv4Address.Merge(m, src)
}
func (m *IPv4Address) XXX_Size() int {
	return xxx_messageInfo_IPv4Address.Size(m)
}
func (m *IPv4Address) XXX_DiscardUnknown() {
	xxx_messageInfo_IPv4Address.DiscardUnknown(m)
}

var xxx_messageInfo_IPv4Address proto.InternalMessageInfo

type isIPv4Address_AddressOneof interface {
	isIPv4Address_AddressOneof()
}

type IPv4Address_U32 struct {
	U32 uint32 `protobuf:"varint,1,opt,name=u32,proto3,oneof"`
}

type IPv4Address_U8 struct {
	U8 []byte `protobuf:"bytes,2,opt,name=u8,proto3,oneof"`
}

func (*IPv4Address_U32) isIPv4Address_AddressOneof() {}

func (*IPv4Address_U8) isIPv4Address_AddressOneof() {}

func (m *IPv4Address) GetAddressOneof() isIPv4Address_AddressOneof {
	if m != nil {
		return m.AddressOneof
	}
	return nil
}

func (m *IPv4Address) GetU32() uint32 {
	if x, ok := m.GetAddressOneof().(*IPv4Address_U32); ok {
		return x.U32
	}
	return 0
}

func (m *IPv4Address) GetU8() []byte {
	if x, ok := m.GetAddressOneof().(*IPv4Address_U8); ok {
		return x.U8
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*IPv4Address) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*IPv4Address_U32)(nil),
		(*IPv4Address_U8)(nil),
	}
}

type SCA_Prefix struct {
	Afi    uint32 `protobuf:"varint,1,opt,name=afi,proto3" json:"afi,omitempty"`
	Safi   uint32 `protobuf:"varint,2,opt,name=safi,proto3" json:"safi,omitempty"`
	Length uint32 `protobuf:"varint,3,opt,name=length,proto3" json:"length,omitempty"`
	// Types that are valid to be assigned to Addr:
	//	*SCA_Prefix_IpV4
	//	*SCA_Prefix_IpV6
	//	*SCA_Prefix_Ip
	Addr                 isSCA_Prefix_Addr `protobuf_oneof:"addr"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *SCA_Prefix) Reset()         { *m = SCA_Prefix{} }
func (m *SCA_Prefix) String() string { return proto.CompactTextString(m) }
func (*SCA_Prefix) ProtoMessage()    {}
func (*SCA_Prefix) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6d819656a476f83, []int{8}
}

func (m *SCA_Prefix) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SCA_Prefix.Unmarshal(m, b)
}
func (m *SCA_Prefix) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SCA_Prefix.Marshal(b, m, deterministic)
}
func (m *SCA_Prefix) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SCA_Prefix.Merge(m, src)
}
func (m *SCA_Prefix) XXX_Size() int {
	return xxx_messageInfo_SCA_Prefix.Size(m)
}
func (m *SCA_Prefix) XXX_DiscardUnknown() {
	xxx_messageInfo_SCA_Prefix.DiscardUnknown(m)
}

var xxx_messageInfo_SCA_Prefix proto.InternalMessageInfo

func (m *SCA_Prefix) GetAfi() uint32 {
	if m != nil {
		return m.Afi
	}
	return 0
}

func (m *SCA_Prefix) GetSafi() uint32 {
	if m != nil {
		return m.Safi
	}
	return 0
}

func (m *SCA_Prefix) GetLength() uint32 {
	if m != nil {
		return m.Length
	}
	return 0
}

type isSCA_Prefix_Addr interface {
	isSCA_Prefix_Addr()
}

type SCA_Prefix_IpV4 struct {
	IpV4 uint32 `protobuf:"varint,4,opt,name=ipV4,proto3,oneof"`
}

type SCA_Prefix_IpV6 struct {
	IpV6 uint64 `protobuf:"varint,5,opt,name=ipV6,proto3,oneof"`
}

type SCA_Prefix_Ip struct {
	Ip []byte `protobuf:"bytes,6,opt,name=ip,proto3,oneof"`
}

func (*SCA_Prefix_IpV4) isSCA_Prefix_Addr() {}

func (*SCA_Prefix_IpV6) isSCA_Prefix_Addr() {}

func (*SCA_Prefix_Ip) isSCA_Prefix_Addr() {}

func (m *SCA_Prefix) GetAddr() isSCA_Prefix_Addr {
	if m != nil {
		return m.Addr
	}
	return nil
}

func (m *SCA_Prefix) GetIpV4() uint32 {
	if x, ok := m.GetAddr().(*SCA_Prefix_IpV4); ok {
		return x.IpV4
	}
	return 0
}

func (m *SCA_Prefix) GetIpV6() uint64 {
	if x, ok := m.GetAddr().(*SCA_Prefix_IpV6); ok {
		return x.IpV6
	}
	return 0
}

func (m *SCA_Prefix) GetIp() []byte {
	if x, ok := m.GetAddr().(*SCA_Prefix_Ip); ok {
		return x.Ip
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*SCA_Prefix) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*SCA_Prefix_IpV4)(nil),
		(*SCA_Prefix_IpV6)(nil),
		(*SCA_Prefix_Ip)(nil),
	}
}

type BGPSEC_DATA_PTR struct {
	LocalAs              uint32   `protobuf:"varint,1,opt,name=local_as,json=localAs,proto3" json:"local_as,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BGPSEC_DATA_PTR) Reset()         { *m = BGPSEC_DATA_PTR{} }
func (m *BGPSEC_DATA_PTR) String() string { return proto.CompactTextString(m) }
func (*BGPSEC_DATA_PTR) ProtoMessage()    {}
func (*BGPSEC_DATA_PTR) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6d819656a476f83, []int{9}
}

func (m *BGPSEC_DATA_PTR) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BGPSEC_DATA_PTR.Unmarshal(m, b)
}
func (m *BGPSEC_DATA_PTR) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BGPSEC_DATA_PTR.Marshal(b, m, deterministic)
}
func (m *BGPSEC_DATA_PTR) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BGPSEC_DATA_PTR.Merge(m, src)
}
func (m *BGPSEC_DATA_PTR) XXX_Size() int {
	return xxx_messageInfo_BGPSEC_DATA_PTR.Size(m)
}
func (m *BGPSEC_DATA_PTR) XXX_DiscardUnknown() {
	xxx_messageInfo_BGPSEC_DATA_PTR.DiscardUnknown(m)
}

var xxx_messageInfo_BGPSEC_DATA_PTR proto.InternalMessageInfo

func (m *BGPSEC_DATA_PTR) GetLocalAs() uint32 {
	if m != nil {
		return m.LocalAs
	}
	return 0
}

type BGPSECValReqData struct {
	NumHops              uint32           `protobuf:"varint,1,opt,name=numHops,proto3" json:"numHops,omitempty"`
	AttrLen              uint32           `protobuf:"varint,2,opt,name=attrLen,proto3" json:"attrLen,omitempty"`
	ValPrefix            *SCA_Prefix      `protobuf:"bytes,3,opt,name=valPrefix,proto3" json:"valPrefix,omitempty"`
	ValData              *BGPSEC_DATA_PTR `protobuf:"bytes,4,opt,name=valData,proto3" json:"valData,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *BGPSECValReqData) Reset()         { *m = BGPSECValReqData{} }
func (m *BGPSECValReqData) String() string { return proto.CompactTextString(m) }
func (*BGPSECValReqData) ProtoMessage()    {}
func (*BGPSECValReqData) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6d819656a476f83, []int{10}
}

func (m *BGPSECValReqData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BGPSECValReqData.Unmarshal(m, b)
}
func (m *BGPSECValReqData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BGPSECValReqData.Marshal(b, m, deterministic)
}
func (m *BGPSECValReqData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BGPSECValReqData.Merge(m, src)
}
func (m *BGPSECValReqData) XXX_Size() int {
	return xxx_messageInfo_BGPSECValReqData.Size(m)
}
func (m *BGPSECValReqData) XXX_DiscardUnknown() {
	xxx_messageInfo_BGPSECValReqData.DiscardUnknown(m)
}

var xxx_messageInfo_BGPSECValReqData proto.InternalMessageInfo

func (m *BGPSECValReqData) GetNumHops() uint32 {
	if m != nil {
		return m.NumHops
	}
	return 0
}

func (m *BGPSECValReqData) GetAttrLen() uint32 {
	if m != nil {
		return m.AttrLen
	}
	return 0
}

func (m *BGPSECValReqData) GetValPrefix() *SCA_Prefix {
	if m != nil {
		return m.ValPrefix
	}
	return nil
}

func (m *BGPSECValReqData) GetValData() *BGPSEC_DATA_PTR {
	if m != nil {
		return m.ValData
	}
	return nil
}

type ProxyVerifyV4Request struct {
	Common               *ProxyBasicHeader `protobuf:"bytes,1,opt,name=common,proto3" json:"common,omitempty"`
	PrefixAddress        *IPv4Address      `protobuf:"bytes,2,opt,name=prefixAddress,proto3" json:"prefixAddress,omitempty"`
	OriginAS             uint32            `protobuf:"varint,3,opt,name=originAS,proto3" json:"originAS,omitempty"`
	BgpsecLength         uint32            `protobuf:"varint,4,opt,name=bgpsecLength,proto3" json:"bgpsecLength,omitempty"`
	BgpsecValReqData     *BGPSECValReqData `protobuf:"bytes,5,opt,name=bgpsecValReqData,proto3" json:"bgpsecValReqData,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ProxyVerifyV4Request) Reset()         { *m = ProxyVerifyV4Request{} }
func (m *ProxyVerifyV4Request) String() string { return proto.CompactTextString(m) }
func (*ProxyVerifyV4Request) ProtoMessage()    {}
func (*ProxyVerifyV4Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6d819656a476f83, []int{11}
}

func (m *ProxyVerifyV4Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProxyVerifyV4Request.Unmarshal(m, b)
}
func (m *ProxyVerifyV4Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProxyVerifyV4Request.Marshal(b, m, deterministic)
}
func (m *ProxyVerifyV4Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProxyVerifyV4Request.Merge(m, src)
}
func (m *ProxyVerifyV4Request) XXX_Size() int {
	return xxx_messageInfo_ProxyVerifyV4Request.Size(m)
}
func (m *ProxyVerifyV4Request) XXX_DiscardUnknown() {
	xxx_messageInfo_ProxyVerifyV4Request.DiscardUnknown(m)
}

var xxx_messageInfo_ProxyVerifyV4Request proto.InternalMessageInfo

func (m *ProxyVerifyV4Request) GetCommon() *ProxyBasicHeader {
	if m != nil {
		return m.Common
	}
	return nil
}

func (m *ProxyVerifyV4Request) GetPrefixAddress() *IPv4Address {
	if m != nil {
		return m.PrefixAddress
	}
	return nil
}

func (m *ProxyVerifyV4Request) GetOriginAS() uint32 {
	if m != nil {
		return m.OriginAS
	}
	return 0
}

func (m *ProxyVerifyV4Request) GetBgpsecLength() uint32 {
	if m != nil {
		return m.BgpsecLength
	}
	return 0
}

func (m *ProxyVerifyV4Request) GetBgpsecValReqData() *BGPSECValReqData {
	if m != nil {
		return m.BgpsecValReqData
	}
	return nil
}

type ProxyVerifyNotify struct {
	Type                 uint32   `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`
	ResultType           uint32   `protobuf:"varint,2,opt,name=resultType,proto3" json:"resultType,omitempty"`
	RoaResult            uint32   `protobuf:"varint,3,opt,name=roaResult,proto3" json:"roaResult,omitempty"`
	BgpsecResult         uint32   `protobuf:"varint,4,opt,name=bgpsecResult,proto3" json:"bgpsecResult,omitempty"`
	AspaResult           uint32   `protobuf:"varint,5,opt,name=aspaResult,proto3" json:"aspaResult,omitempty"`
	Reserved             uint32   `protobuf:"varint,6,opt,name=reserved,proto3" json:"reserved,omitempty"`
	Zero                 uint32   `protobuf:"varint,7,opt,name=zero,proto3" json:"zero,omitempty"`
	Length               uint32   `protobuf:"varint,8,opt,name=length,proto3" json:"length,omitempty"`
	RequestToken         uint32   `protobuf:"varint,9,opt,name=requestToken,proto3" json:"requestToken,omitempty"`
	UpdateID             uint32   `protobuf:"varint,10,opt,name=updateID,proto3" json:"updateID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProxyVerifyNotify) Reset()         { *m = ProxyVerifyNotify{} }
func (m *ProxyVerifyNotify) String() string { return proto.CompactTextString(m) }
func (*ProxyVerifyNotify) ProtoMessage()    {}
func (*ProxyVerifyNotify) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6d819656a476f83, []int{12}
}

func (m *ProxyVerifyNotify) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProxyVerifyNotify.Unmarshal(m, b)
}
func (m *ProxyVerifyNotify) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProxyVerifyNotify.Marshal(b, m, deterministic)
}
func (m *ProxyVerifyNotify) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProxyVerifyNotify.Merge(m, src)
}
func (m *ProxyVerifyNotify) XXX_Size() int {
	return xxx_messageInfo_ProxyVerifyNotify.Size(m)
}
func (m *ProxyVerifyNotify) XXX_DiscardUnknown() {
	xxx_messageInfo_ProxyVerifyNotify.DiscardUnknown(m)
}

var xxx_messageInfo_ProxyVerifyNotify proto.InternalMessageInfo

func (m *ProxyVerifyNotify) GetType() uint32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *ProxyVerifyNotify) GetResultType() uint32 {
	if m != nil {
		return m.ResultType
	}
	return 0
}

func (m *ProxyVerifyNotify) GetRoaResult() uint32 {
	if m != nil {
		return m.RoaResult
	}
	return 0
}

func (m *ProxyVerifyNotify) GetBgpsecResult() uint32 {
	if m != nil {
		return m.BgpsecResult
	}
	return 0
}

func (m *ProxyVerifyNotify) GetAspaResult() uint32 {
	if m != nil {
		return m.AspaResult
	}
	return 0
}

func (m *ProxyVerifyNotify) GetReserved() uint32 {
	if m != nil {
		return m.Reserved
	}
	return 0
}

func (m *ProxyVerifyNotify) GetZero() uint32 {
	if m != nil {
		return m.Zero
	}
	return 0
}

func (m *ProxyVerifyNotify) GetLength() uint32 {
	if m != nil {
		return m.Length
	}
	return 0
}

func (m *ProxyVerifyNotify) GetRequestToken() uint32 {
	if m != nil {
		return m.RequestToken
	}
	return 0
}

func (m *ProxyVerifyNotify) GetUpdateID() uint32 {
	if m != nil {
		return m.UpdateID
	}
	return 0
}

type ProxyVerifyRequest struct {
	Data                 []byte   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Length               uint32   `protobuf:"varint,2,opt,name=length,proto3" json:"length,omitempty"`
	GrpcClientID         uint32   `protobuf:"varint,3,opt,name=grpcClientID,proto3" json:"grpcClientID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProxyVerifyRequest) Reset()         { *m = ProxyVerifyRequest{} }
func (m *ProxyVerifyRequest) String() string { return proto.CompactTextString(m) }
func (*ProxyVerifyRequest) ProtoMessage()    {}
func (*ProxyVerifyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6d819656a476f83, []int{13}
}

func (m *ProxyVerifyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProxyVerifyRequest.Unmarshal(m, b)
}
func (m *ProxyVerifyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProxyVerifyRequest.Marshal(b, m, deterministic)
}
func (m *ProxyVerifyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProxyVerifyRequest.Merge(m, src)
}
func (m *ProxyVerifyRequest) XXX_Size() int {
	return xxx_messageInfo_ProxyVerifyRequest.Size(m)
}
func (m *ProxyVerifyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ProxyVerifyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ProxyVerifyRequest proto.InternalMessageInfo

func (m *ProxyVerifyRequest) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *ProxyVerifyRequest) GetLength() uint32 {
	if m != nil {
		return m.Length
	}
	return 0
}

func (m *ProxyVerifyRequest) GetGrpcClientID() uint32 {
	if m != nil {
		return m.GrpcClientID
	}
	return 0
}

func init() {
	proto.RegisterType((*PduRequest)(nil), "srx_grpc_v6.PduRequest")
	proto.RegisterType((*PduResponse)(nil), "srx_grpc_v6.PduResponse")
	proto.RegisterType((*ProxyHelloRequest)(nil), "srx_grpc_v6.ProxyHelloRequest")
	proto.RegisterType((*ProxyHelloResponse)(nil), "srx_grpc_v6.ProxyHelloResponse")
	proto.RegisterType((*ProxyGoodByeRequest)(nil), "srx_grpc_v6.ProxyGoodByeRequest")
	proto.RegisterType((*ProxyGoodByeResponse)(nil), "srx_grpc_v6.ProxyGoodByeResponse")
	proto.RegisterType((*ProxyBasicHeader)(nil), "srx_grpc_v6.ProxyBasicHeader")
	proto.RegisterType((*IPv4Address)(nil), "srx_grpc_v6.IPv4Address")
	proto.RegisterType((*SCA_Prefix)(nil), "srx_grpc_v6.SCA_Prefix")
	proto.RegisterType((*BGPSEC_DATA_PTR)(nil), "srx_grpc_v6.BGPSEC_DATA_PTR")
	proto.RegisterType((*BGPSECValReqData)(nil), "srx_grpc_v6.BGPSECValReqData")
	proto.RegisterType((*ProxyVerifyV4Request)(nil), "srx_grpc_v6.ProxyVerifyV4Request")
	proto.RegisterType((*ProxyVerifyNotify)(nil), "srx_grpc_v6.ProxyVerifyNotify")
	proto.RegisterType((*ProxyVerifyRequest)(nil), "srx_grpc_v6.ProxyVerifyRequest")
}

func init() { proto.RegisterFile("srx_grpc_v6.proto", fileDescriptor_c6d819656a476f83) }

var fileDescriptor_c6d819656a476f83 = []byte{
	// 1065 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x57, 0x4f, 0x6f, 0xe3, 0x44,
	0x14, 0x6f, 0x9a, 0x36, 0x69, 0x5e, 0x12, 0x9a, 0x0e, 0xa5, 0x98, 0xa8, 0x74, 0x8b, 0x4f, 0x95,
	0x40, 0x15, 0xca, 0x76, 0xab, 0x9e, 0x90, 0x92, 0x06, 0x6d, 0x22, 0x2a, 0x88, 0xc6, 0xa1, 0xcb,
	0x2d, 0x9a, 0x8d, 0x27, 0xc1, 0xaa, 0xeb, 0xf1, 0xce, 0x8c, 0x43, 0xc2, 0x87, 0x40, 0x1c, 0xf9,
	0x10, 0x5c, 0x90, 0xe0, 0xc3, 0x71, 0x43, 0xf3, 0x27, 0xb1, 0x9d, 0xb4, 0x95, 0xb6, 0x70, 0xe0,
	0x36, 0xef, 0xcd, 0x9b, 0x79, 0xbf, 0xdf, 0xfb, 0x37, 0x36, 0x1c, 0x08, 0x3e, 0x1f, 0x4d, 0x79,
	0x3c, 0x1e, 0xcd, 0x2e, 0xcf, 0x63, 0xce, 0x24, 0x43, 0xd5, 0x8c, 0xca, 0xbd, 0x02, 0x18, 0xf8,
	0x09, 0xa6, 0xef, 0x12, 0x2a, 0x24, 0x42, 0xb0, 0xe3, 0x13, 0x49, 0x9c, 0xc2, 0x69, 0xe1, 0xac,
	0x86, 0xf5, 0x1a, 0x1d, 0x41, 0x29, 0xa4, 0xd1, 0x54, 0xfe, 0xe8, 0x6c, 0x9f, 0x16, 0xce, 0xea,
	0xd8, 0x4a, 0xee, 0x04, 0xaa, 0xfa, 0xa4, 0x88, 0x59, 0x24, 0xe8, 0xfb, 0x1c, 0x45, 0x9f, 0xc3,
	0xc1, 0x8c, 0x84, 0x81, 0x4f, 0x64, 0xc0, 0xa2, 0x91, 0x90, 0x44, 0x26, 0xc2, 0x29, 0x6a, 0x93,
	0x46, 0xba, 0xe1, 0x69, 0xbd, 0xfb, 0x77, 0x01, 0x0e, 0x06, 0x9c, 0xcd, 0x17, 0x3d, 0x1a, 0x86,
	0x2c, 0x83, 0x54, 0x2e, 0x62, 0xaa, 0xdd, 0xd5, 0xb1, 0x5e, 0x23, 0x07, 0xca, 0x33, 0xca, 0x45,
	0xc0, 0x22, 0xeb, 0x6f, 0x29, 0xa2, 0x26, 0xec, 0x71, 0x2a, 0x28, 0x9f, 0x51, 0xdf, 0xfa, 0x59,
	0xc9, 0xea, 0xa6, 0x9f, 0x29, 0x67, 0xce, 0x8e, 0xb9, 0x49, 0xad, 0x33, 0xc0, 0x77, 0x73, 0xc0,
	0xcf, 0x60, 0x3f, 0x56, 0x50, 0xfa, 0x3e, 0x8d, 0x64, 0x30, 0x09, 0x28, 0x77, 0x4a, 0xda, 0x60,
	0x5d, 0x8d, 0x1a, 0x50, 0x24, 0x22, 0x72, 0xca, 0x7a, 0x57, 0x2d, 0x15, 0x86, 0x88, 0x0d, 0x28,
	0xe5, 0x6d, 0xcf, 0xd9, 0x33, 0x18, 0x96, 0xb2, 0xf2, 0x17, 0x9b, 0x9d, 0x8a, 0xf1, 0x67, 0x24,
	0xf7, 0xcf, 0x02, 0xa0, 0x2c, 0xf7, 0x34, 0xd6, 0xff, 0x67, 0xf2, 0xee, 0x5f, 0x05, 0xf8, 0x50,
	0xc3, 0x7e, 0xcd, 0x98, 0xdf, 0x59, 0xd0, 0xa7, 0x92, 0x76, 0x02, 0x70, 0x47, 0x69, 0xfc, 0x26,
	0x88, 0x7c, 0xf6, 0x93, 0x85, 0x9e, 0xd1, 0xfc, 0x67, 0xe8, 0x5d, 0xa8, 0xa9, 0x9a, 0xbf, 0x0e,
	0x03, 0x1a, 0xc9, 0x7e, 0xd7, 0x42, 0xcf, 0xe9, 0xdc, 0x73, 0x38, 0xcc, 0xc3, 0xb6, 0xf1, 0x3e,
	0x82, 0x92, 0x2d, 0x52, 0x85, 0x7c, 0x0f, 0x5b, 0xc9, 0xfd, 0xbd, 0x08, 0x0d, 0x7d, 0xa0, 0x43,
	0x44, 0x30, 0xee, 0x51, 0xe2, 0x53, 0xfe, 0x20, 0xc9, 0x43, 0xd8, 0x9d, 0x84, 0x64, 0x2a, 0x2c,
	0x3f, 0x23, 0xa0, 0x63, 0xa8, 0x70, 0x46, 0x30, 0x15, 0x1e, 0x1f, 0x5b, 0x6e, 0xa9, 0x42, 0x01,
	0x7e, 0x3b, 0x8d, 0x05, 0x1d, 0x5b, 0x03, 0x43, 0x32, 0xa7, 0x53, 0xc1, 0x23, 0x22, 0x5e, 0x5e,
	0x61, 0x08, 0x67, 0x34, 0xb9, 0xe0, 0x95, 0xd6, 0x82, 0x77, 0x04, 0x25, 0x22, 0x86, 0x0a, 0xa9,
	0x29, 0x52, 0x2b, 0x29, 0x54, 0x44, 0x60, 0x1a, 0xea, 0x2d, 0x53, 0xa8, 0xa9, 0x22, 0x13, 0xde,
	0x4a, 0x2e, 0xbc, 0x86, 0x4b, 0x97, 0x4e, 0x30, 0x15, 0x0e, 0xac, 0xb8, 0x18, 0x45, 0xca, 0xc5,
	0x1a, 0x54, 0xb3, 0x5c, 0xac, 0x8d, 0xe5, 0x62, 0x2d, 0x6a, 0x29, 0x17, 0xbb, 0x7f, 0x0c, 0x95,
	0x98, 0xd3, 0x49, 0x30, 0xbf, 0xa1, 0x91, 0x53, 0x37, 0x1e, 0x56, 0x0a, 0xe5, 0x81, 0x9b, 0x2a,
	0x1b, 0xb2, 0x3b, 0x1a, 0x39, 0x1f, 0x18, 0x0f, 0x59, 0x9d, 0xdb, 0x85, 0x6a, 0x7f, 0x30, 0xbb,
	0x68, 0xfb, 0x3e, 0xa7, 0x42, 0x20, 0x04, 0xc5, 0xe4, 0x65, 0xcb, 0xe4, 0xa9, 0xb7, 0x85, 0x95,
	0x80, 0x1a, 0xb0, 0x9d, 0x5c, 0xe9, 0x2c, 0xd5, 0x7a, 0x5b, 0x78, 0x3b, 0xb9, 0xea, 0xec, 0x43,
	0x9d, 0x98, 0x03, 0x23, 0x16, 0x51, 0x36, 0x71, 0x7f, 0x2d, 0x00, 0x78, 0xd7, 0xed, 0xd1, 0x40,
	0xfb, 0xd6, 0x8d, 0x3e, 0x09, 0x6c, 0xb6, 0xd5, 0x52, 0x15, 0x80, 0x50, 0x2a, 0x93, 0x6b, 0xbd,
	0xce, 0x84, 0xad, 0x98, 0x0b, 0xdb, 0x21, 0xec, 0x04, 0xf1, 0xed, 0x85, 0x49, 0x6e, 0x6f, 0x0b,
	0x6b, 0xc9, 0x6a, 0x2f, 0x75, 0x42, 0x77, 0xac, 0xf6, 0x52, 0x61, 0x0b, 0x62, 0x9d, 0x46, 0x8d,
	0x2d, 0x88, 0x3b, 0x25, 0xd8, 0x51, 0xd8, 0xdc, 0x2f, 0x60, 0xbf, 0xf3, 0x7a, 0xe0, 0x7d, 0x7d,
	0x3d, 0xea, 0xb6, 0x87, 0xed, 0xd1, 0x60, 0x88, 0xd1, 0x27, 0xb0, 0x17, 0xb2, 0x31, 0x09, 0x47,
	0x44, 0x58, 0x6c, 0x65, 0x2d, 0xb7, 0x85, 0xea, 0xce, 0x86, 0x31, 0xbf, 0x25, 0x21, 0xa6, 0xef,
	0xba, 0x6a, 0x54, 0x3b, 0x50, 0x8e, 0x92, 0xfb, 0x1e, 0x8b, 0x57, 0xe6, 0x56, 0x54, 0x3b, 0x44,
	0x4a, 0xae, 0xa2, 0x6e, 0x07, 0x8b, 0x15, 0xd1, 0x2b, 0xa8, 0xcc, 0x48, 0x68, 0xe2, 0xa0, 0x79,
	0x55, 0x5b, 0x1f, 0x9f, 0x67, 0xdf, 0x9b, 0x34, 0x4c, 0x38, 0xb5, 0x44, 0x97, 0x50, 0x9e, 0x91,
	0x50, 0x79, 0xd5, 0xb4, 0xab, 0xad, 0xe3, 0xdc, 0xa1, 0x35, 0x26, 0x78, 0x69, 0xec, 0xfe, 0xb6,
	0x6d, 0xdb, 0xf3, 0x96, 0xf2, 0x60, 0xb2, 0xb8, 0xbd, 0x58, 0x8e, 0x95, 0x57, 0x50, 0x1a, 0xb3,
	0xfb, 0x7b, 0x16, 0x69, 0xe8, 0xd5, 0xd6, 0xa7, 0xb9, 0xfb, 0xd6, 0x1b, 0x14, 0x5b, 0x63, 0xf4,
	0x15, 0xd4, 0x4d, 0xfd, 0xd8, 0x82, 0xd0, 0xf4, 0xaa, 0x2d, 0x27, 0x77, 0x3a, 0x53, 0x30, 0x38,
	0x6f, 0xae, 0x9a, 0x8b, 0xf1, 0x60, 0x1a, 0x44, 0x6d, 0x6f, 0x39, 0x99, 0x96, 0x72, 0x5a, 0xf0,
	0x37, 0x26, 0xeb, 0xb9, 0xe6, 0x35, 0x3a, 0xd4, 0x87, 0x86, 0x91, 0xd3, 0x34, 0xe8, 0x8c, 0xaf,
	0x13, 0x58, 0xcf, 0x15, 0xde, 0x38, 0xe6, 0xfe, 0xb1, 0x6d, 0xdf, 0x48, 0x13, 0x9a, 0x6f, 0x99,
	0x0c, 0x26, 0x8b, 0xc7, 0xc6, 0x2d, 0xa7, 0x22, 0x09, 0xa5, 0x6e, 0x6f, 0x3b, 0x6e, 0x53, 0x4d,
	0x3a, 0x93, 0x92, 0x50, 0xe6, 0x67, 0x52, 0x12, 0xca, 0xdc, 0x4c, 0x52, 0x06, 0xeb, 0x33, 0x49,
	0xd9, 0xa4, 0x33, 0x49, 0x59, 0xe4, 0x67, 0x92, 0xda, 0x7f, 0x6a, 0x26, 0x2d, 0x07, 0x7a, 0xf9,
	0xc1, 0x81, 0xbe, 0xb7, 0x3e, 0xd0, 0x73, 0x1d, 0x5f, 0xd9, 0xec, 0x78, 0xe5, 0x2b, 0x89, 0x7d,
	0x22, 0x69, 0xbf, 0x6b, 0x87, 0xd2, 0x4a, 0x76, 0x7d, 0xfb, 0xb4, 0x9a, 0x90, 0x3d, 0xe3, 0x0b,
	0x68, 0xe3, 0x49, 0x29, 0x6e, 0x3e, 0x29, 0xad, 0x5f, 0x76, 0xa1, 0xe4, 0xe1, 0x79, 0x3b, 0x0e,
	0xd0, 0x0d, 0x7c, 0xe4, 0xd1, 0xc8, 0x1f, 0x90, 0xf1, 0x1d, 0x95, 0x43, 0xe6, 0xe1, 0xb9, 0xa7,
	0x58, 0x73, 0x94, 0x6f, 0x9a, 0xf4, 0x73, 0xac, 0xe9, 0x6c, 0x6e, 0x98, 0x17, 0xc9, 0xdd, 0x42,
	0xdf, 0x00, 0x52, 0xb7, 0xb5, 0x23, 0xff, 0x0d, 0x09, 0xe4, 0x80, 0xb3, 0xb1, 0xaa, 0xc9, 0xe7,
	0x5c, 0xf5, 0x65, 0x01, 0x7d, 0x07, 0x90, 0x7e, 0x66, 0xa0, 0x93, 0xcd, 0xfe, 0xc9, 0x7e, 0x7b,
	0x35, 0x5f, 0x3c, 0xba, 0xbf, 0x42, 0xf7, 0x3d, 0xd4, 0xb2, 0x2f, 0x29, 0x3a, 0xdd, 0x3c, 0x92,
	0xff, 0x36, 0x68, 0x7e, 0xf6, 0x84, 0x45, 0x96, 0x74, 0x76, 0xc7, 0x93, 0x9c, 0x92, 0xfb, 0xe7,
	0x92, 0x1e, 0x42, 0x35, 0x53, 0x00, 0xe8, 0x01, 0x00, 0x6b, 0x83, 0xa6, 0x79, 0xf2, 0x98, 0x89,
	0x69, 0x38, 0x7d, 0xeb, 0x0f, 0xb9, 0x4e, 0xb4, 0x08, 0x5f, 0x3c, 0x76, 0xf0, 0x7d, 0x6e, 0xee,
	0x5a, 0xbc, 0xff, 0x8a, 0xf5, 0xdb, 0x92, 0xfe, 0x09, 0x78, 0xf9, 0x4f, 0x00, 0x00, 0x00, 0xff,
	0xff, 0xbf, 0x2b, 0x0a, 0xca, 0x19, 0x0c, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SRxApiClient is the client API for SRxApi service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SRxApiClient interface {
	SendPacketToSRxServer(ctx context.Context, in *PduRequest, opts ...grpc.CallOption) (*PduResponse, error)
	SendAndWaitProcess(ctx context.Context, in *PduRequest, opts ...grpc.CallOption) (SRxApi_SendAndWaitProcessClient, error)
	ProxyHello(ctx context.Context, in *ProxyHelloRequest, opts ...grpc.CallOption) (*ProxyHelloResponse, error)
	ProxyGoodBye(ctx context.Context, in *ProxyGoodByeRequest, opts ...grpc.CallOption) (*ProxyGoodByeResponse, error)
	ProxyGoodByeStream(ctx context.Context, in *PduRequest, opts ...grpc.CallOption) (SRxApi_ProxyGoodByeStreamClient, error)
	ProxyVerify(ctx context.Context, in *ProxyVerifyV4Request, opts ...grpc.CallOption) (SRxApi_ProxyVerifyClient, error)
	ProxyVerifyStream(ctx context.Context, in *ProxyVerifyRequest, opts ...grpc.CallOption) (SRxApi_ProxyVerifyStreamClient, error)
	ProxyStream(ctx context.Context, in *PduRequest, opts ...grpc.CallOption) (SRxApi_ProxyStreamClient, error)
}

type sRxApiClient struct {
	cc *grpc.ClientConn
}

func NewSRxApiClient(cc *grpc.ClientConn) SRxApiClient {
	return &sRxApiClient{cc}
}

func (c *sRxApiClient) SendPacketToSRxServer(ctx context.Context, in *PduRequest, opts ...grpc.CallOption) (*PduResponse, error) {
	out := new(PduResponse)
	err := c.cc.Invoke(ctx, "/srx_grpc_v6.SRxApi/SendPacketToSRxServer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sRxApiClient) SendAndWaitProcess(ctx context.Context, in *PduRequest, opts ...grpc.CallOption) (SRxApi_SendAndWaitProcessClient, error) {
	stream, err := c.cc.NewStream(ctx, &_SRxApi_serviceDesc.Streams[0], "/srx_grpc_v6.SRxApi/SendAndWaitProcess", opts...)
	if err != nil {
		return nil, err
	}
	x := &sRxApiSendAndWaitProcessClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type SRxApi_SendAndWaitProcessClient interface {
	Recv() (*PduResponse, error)
	grpc.ClientStream
}

type sRxApiSendAndWaitProcessClient struct {
	grpc.ClientStream
}

func (x *sRxApiSendAndWaitProcessClient) Recv() (*PduResponse, error) {
	m := new(PduResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *sRxApiClient) ProxyHello(ctx context.Context, in *ProxyHelloRequest, opts ...grpc.CallOption) (*ProxyHelloResponse, error) {
	out := new(ProxyHelloResponse)
	err := c.cc.Invoke(ctx, "/srx_grpc_v6.SRxApi/ProxyHello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sRxApiClient) ProxyGoodBye(ctx context.Context, in *ProxyGoodByeRequest, opts ...grpc.CallOption) (*ProxyGoodByeResponse, error) {
	out := new(ProxyGoodByeResponse)
	err := c.cc.Invoke(ctx, "/srx_grpc_v6.SRxApi/ProxyGoodBye", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sRxApiClient) ProxyGoodByeStream(ctx context.Context, in *PduRequest, opts ...grpc.CallOption) (SRxApi_ProxyGoodByeStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &_SRxApi_serviceDesc.Streams[1], "/srx_grpc_v6.SRxApi/ProxyGoodByeStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &sRxApiProxyGoodByeStreamClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type SRxApi_ProxyGoodByeStreamClient interface {
	Recv() (*PduResponse, error)
	grpc.ClientStream
}

type sRxApiProxyGoodByeStreamClient struct {
	grpc.ClientStream
}

func (x *sRxApiProxyGoodByeStreamClient) Recv() (*PduResponse, error) {
	m := new(PduResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *sRxApiClient) ProxyVerify(ctx context.Context, in *ProxyVerifyV4Request, opts ...grpc.CallOption) (SRxApi_ProxyVerifyClient, error) {
	stream, err := c.cc.NewStream(ctx, &_SRxApi_serviceDesc.Streams[2], "/srx_grpc_v6.SRxApi/ProxyVerify", opts...)
	if err != nil {
		return nil, err
	}
	x := &sRxApiProxyVerifyClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type SRxApi_ProxyVerifyClient interface {
	Recv() (*ProxyVerifyNotify, error)
	grpc.ClientStream
}

type sRxApiProxyVerifyClient struct {
	grpc.ClientStream
}

func (x *sRxApiProxyVerifyClient) Recv() (*ProxyVerifyNotify, error) {
	m := new(ProxyVerifyNotify)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *sRxApiClient) ProxyVerifyStream(ctx context.Context, in *ProxyVerifyRequest, opts ...grpc.CallOption) (SRxApi_ProxyVerifyStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &_SRxApi_serviceDesc.Streams[3], "/srx_grpc_v6.SRxApi/ProxyVerifyStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &sRxApiProxyVerifyStreamClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type SRxApi_ProxyVerifyStreamClient interface {
	Recv() (*ProxyVerifyNotify, error)
	grpc.ClientStream
}

type sRxApiProxyVerifyStreamClient struct {
	grpc.ClientStream
}

func (x *sRxApiProxyVerifyStreamClient) Recv() (*ProxyVerifyNotify, error) {
	m := new(ProxyVerifyNotify)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *sRxApiClient) ProxyStream(ctx context.Context, in *PduRequest, opts ...grpc.CallOption) (SRxApi_ProxyStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &_SRxApi_serviceDesc.Streams[4], "/srx_grpc_v6.SRxApi/ProxyStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &sRxApiProxyStreamClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type SRxApi_ProxyStreamClient interface {
	Recv() (*PduResponse, error)
	grpc.ClientStream
}

type sRxApiProxyStreamClient struct {
	grpc.ClientStream
}

func (x *sRxApiProxyStreamClient) Recv() (*PduResponse, error) {
	m := new(PduResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// SRxApiServer is the server API for SRxApi service.
type SRxApiServer interface {
	SendPacketToSRxServer(context.Context, *PduRequest) (*PduResponse, error)
	SendAndWaitProcess(*PduRequest, SRxApi_SendAndWaitProcessServer) error
	ProxyHello(context.Context, *ProxyHelloRequest) (*ProxyHelloResponse, error)
	ProxyGoodBye(context.Context, *ProxyGoodByeRequest) (*ProxyGoodByeResponse, error)
	ProxyGoodByeStream(*PduRequest, SRxApi_ProxyGoodByeStreamServer) error
	ProxyVerify(*ProxyVerifyV4Request, SRxApi_ProxyVerifyServer) error
	ProxyVerifyStream(*ProxyVerifyRequest, SRxApi_ProxyVerifyStreamServer) error
	ProxyStream(*PduRequest, SRxApi_ProxyStreamServer) error
}

// UnimplementedSRxApiServer can be embedded to have forward compatible implementations.
type UnimplementedSRxApiServer struct {
}

func (*UnimplementedSRxApiServer) SendPacketToSRxServer(ctx context.Context, req *PduRequest) (*PduResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendPacketToSRxServer not implemented")
}
func (*UnimplementedSRxApiServer) SendAndWaitProcess(req *PduRequest, srv SRxApi_SendAndWaitProcessServer) error {
	return status.Errorf(codes.Unimplemented, "method SendAndWaitProcess not implemented")
}
func (*UnimplementedSRxApiServer) ProxyHello(ctx context.Context, req *ProxyHelloRequest) (*ProxyHelloResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProxyHello not implemented")
}
func (*UnimplementedSRxApiServer) ProxyGoodBye(ctx context.Context, req *ProxyGoodByeRequest) (*ProxyGoodByeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProxyGoodBye not implemented")
}
func (*UnimplementedSRxApiServer) ProxyGoodByeStream(req *PduRequest, srv SRxApi_ProxyGoodByeStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method ProxyGoodByeStream not implemented")
}
func (*UnimplementedSRxApiServer) ProxyVerify(req *ProxyVerifyV4Request, srv SRxApi_ProxyVerifyServer) error {
	return status.Errorf(codes.Unimplemented, "method ProxyVerify not implemented")
}
func (*UnimplementedSRxApiServer) ProxyVerifyStream(req *ProxyVerifyRequest, srv SRxApi_ProxyVerifyStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method ProxyVerifyStream not implemented")
}
func (*UnimplementedSRxApiServer) ProxyStream(req *PduRequest, srv SRxApi_ProxyStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method ProxyStream not implemented")
}

func RegisterSRxApiServer(s *grpc.Server, srv SRxApiServer) {
	s.RegisterService(&_SRxApi_serviceDesc, srv)
}

func _SRxApi_SendPacketToSRxServer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PduRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SRxApiServer).SendPacketToSRxServer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/srx_grpc_v6.SRxApi/SendPacketToSRxServer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SRxApiServer).SendPacketToSRxServer(ctx, req.(*PduRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SRxApi_SendAndWaitProcess_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(PduRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SRxApiServer).SendAndWaitProcess(m, &sRxApiSendAndWaitProcessServer{stream})
}

type SRxApi_SendAndWaitProcessServer interface {
	Send(*PduResponse) error
	grpc.ServerStream
}

type sRxApiSendAndWaitProcessServer struct {
	grpc.ServerStream
}

func (x *sRxApiSendAndWaitProcessServer) Send(m *PduResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _SRxApi_ProxyHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProxyHelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SRxApiServer).ProxyHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/srx_grpc_v6.SRxApi/ProxyHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SRxApiServer).ProxyHello(ctx, req.(*ProxyHelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SRxApi_ProxyGoodBye_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProxyGoodByeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SRxApiServer).ProxyGoodBye(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/srx_grpc_v6.SRxApi/ProxyGoodBye",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SRxApiServer).ProxyGoodBye(ctx, req.(*ProxyGoodByeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SRxApi_ProxyGoodByeStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(PduRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SRxApiServer).ProxyGoodByeStream(m, &sRxApiProxyGoodByeStreamServer{stream})
}

type SRxApi_ProxyGoodByeStreamServer interface {
	Send(*PduResponse) error
	grpc.ServerStream
}

type sRxApiProxyGoodByeStreamServer struct {
	grpc.ServerStream
}

func (x *sRxApiProxyGoodByeStreamServer) Send(m *PduResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _SRxApi_ProxyVerify_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ProxyVerifyV4Request)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SRxApiServer).ProxyVerify(m, &sRxApiProxyVerifyServer{stream})
}

type SRxApi_ProxyVerifyServer interface {
	Send(*ProxyVerifyNotify) error
	grpc.ServerStream
}

type sRxApiProxyVerifyServer struct {
	grpc.ServerStream
}

func (x *sRxApiProxyVerifyServer) Send(m *ProxyVerifyNotify) error {
	return x.ServerStream.SendMsg(m)
}

func _SRxApi_ProxyVerifyStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ProxyVerifyRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SRxApiServer).ProxyVerifyStream(m, &sRxApiProxyVerifyStreamServer{stream})
}

type SRxApi_ProxyVerifyStreamServer interface {
	Send(*ProxyVerifyNotify) error
	grpc.ServerStream
}

type sRxApiProxyVerifyStreamServer struct {
	grpc.ServerStream
}

func (x *sRxApiProxyVerifyStreamServer) Send(m *ProxyVerifyNotify) error {
	return x.ServerStream.SendMsg(m)
}

func _SRxApi_ProxyStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(PduRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SRxApiServer).ProxyStream(m, &sRxApiProxyStreamServer{stream})
}

type SRxApi_ProxyStreamServer interface {
	Send(*PduResponse) error
	grpc.ServerStream
}

type sRxApiProxyStreamServer struct {
	grpc.ServerStream
}

func (x *sRxApiProxyStreamServer) Send(m *PduResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _SRxApi_serviceDesc = grpc.ServiceDesc{
	ServiceName: "srx_grpc_v6.SRxApi",
	HandlerType: (*SRxApiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendPacketToSRxServer",
			Handler:    _SRxApi_SendPacketToSRxServer_Handler,
		},
		{
			MethodName: "ProxyHello",
			Handler:    _SRxApi_ProxyHello_Handler,
		},
		{
			MethodName: "ProxyGoodBye",
			Handler:    _SRxApi_ProxyGoodBye_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SendAndWaitProcess",
			Handler:       _SRxApi_SendAndWaitProcess_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ProxyGoodByeStream",
			Handler:       _SRxApi_ProxyGoodByeStream_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ProxyVerify",
			Handler:       _SRxApi_ProxyVerify_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ProxyVerifyStream",
			Handler:       _SRxApi_ProxyVerifyStream_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ProxyStream",
			Handler:       _SRxApi_ProxyStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "srx_grpc_v6.proto",
}
